// gen_oceanslab.mjs — writes new OceanSlab.jsx
import { writeFileSync } from 'fs';

const SQ = "'";  // single quote shorthand to avoid quoting issues

const code = [
`import { useEffect, useRef } from 'react';`,
`import * as THREE from 'three';`,
`import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';`,
``,
`// ─── Public exports used by OceanWorkspace ────────────────────────────────`,
`export const DEPTH_BINS = [0, 10, 50, 100, 200, 500, 1000];`,
`export const TEMP_RELIEF_SCALE = 1.8;`,
``,
`export function computeElevation(temperature, min_temp, temp_range, depth_m, verticalExag = 35) {`,
`  const n = Math.max(0, Math.min(1, (temperature - min_temp) / Math.max(temp_range, 0.0001)));`,
`  const relief = n * TEMP_RELIEF_SCALE * (verticalExag / 35);`,
`  const depthNorm = Math.pow(Math.min(Math.max(0, depth_m), 1000) / 1000, 0.45);`,
`  return (4.8 - depthNorm * 9.6) + (relief - TEMP_RELIEF_SCALE * 0.5);`,
`}`,
``,
`// ─── Scientific colour ramps ──────────────────────────────────────────────`,
`const STOPS = {`,
`  temperature: ['#0033cc','#00b4d8','#00e08c','#ffd166','#ff7700','#f54375'],`,
`  salinity:    ['#03045e','#0077b6','#00b4d8','#90e0ef','#e0aaff','#7209b7'],`,
`  currents:    ['#051923','#006494','#00a6fb','#0582ca','#00f5d4','#70e000'],`,
`  chlorophyll: ['#081c15','#1b4332','#2d6a4f','#52b788','#95d5b2','#d8f3dc'],`,
`  oxygen:      ['#3a0ca3','#4361ee','#4cc9f0','#70e000','#ffaa00','#ff0054'],`,
`  ph:          ['#d00000','#e85d04','#ffba08','#52b788','#0077b6','#03045e'],`,
`  nitrate:     ['#0d1b2a','#1b263b','#415a77','#778da9','#e0e1dd','#38b000'],`,
`  pco2:        ['#f72585','#b5179e','#7209b7','#560bad','#480ca8','#3a0ca3'],`,
`  anomaly:     ['#0022ff','#0088cc','#00ccaa','#666666','#ff6600','#ff0022'],`,
`};`,
``,
`// ─── Helpers ──────────────────────────────────────────────────────────────`,
`function depthToY(d) {`,
`  return 4.8 - Math.pow(Math.min(Math.max(0, d), 1000) / 1000, 0.45) * 9.6;`,
`}`,
``,
`function valueFor(pt, variable) {`,
`  if (variable === 'currents') return Math.hypot(Number(pt?.current_u_ms ?? pt?.uo ?? 0), Number(pt?.current_v_ms ?? pt?.vo ?? 0));`,
`  const a = { temperature:['temperature_c','temperature','thetao','temp'], salinity:['salinity_psu','salinity','so'], currents:['current_speed','velocity'], chlorophyll:['chlorophyll_mgl','chlorophyll','chl'], oxygen:['oxygen_mmolm3','oxygen','dissolved_oxygen','o2'], ph:['ph','pH'], nitrate:['nitrate_mmolm3','nitrate','no3'], pco2:['pco2_uatm','pco2','spco2'] };`,
`  const key = (a[variable] || a.temperature).find((n) => pt?.[n] != null);`,
`  const v = Number(pt?.[key]);`,
`  return Number.isFinite(v) ? v : NaN;`,
`}`,
``,
`function lerpColor(t, pal) {`,
`  const c = Math.max(0, Math.min(1, t)), n = pal.length - 1;`,
`  const s = Math.min(Math.floor(c * n), n - 1);`,
`  return new THREE.Color(pal[s]).lerp(new THREE.Color(pal[s + 1]), (c - s / n) * n);`,
`}`,
``,
`function colorFor(v, lo, hi, variable) {`,
`  return lerpColor((v - lo) / Math.max(hi - lo, 1e-4), STOPS[variable] || STOPS.temperature);`,
`}`,
``,
`function anomalyColor(a, thr = 2) {`,
`  const w = Math.max(thr * 2, 1e-3);`,
`  return lerpColor(Math.max(0, Math.min(1, (a + w) / (w * 2))), STOPS.anomaly);`,
`}`,
``,
`// ═══════════════════════════════════════════════════════════════════════════`,
`// SEABED TERRAIN — procedural multi-octave smooth bathymetry`,
`// Deterministic for same region (seed from bounds).`,
`// Contains: basins, a ridge, a trench, continental-edge thickening, undulations.`,
`// NO random spikes. All smooth trigonometric functions.`,
`// ═══════════════════════════════════════════════════════════════════════════`,
`const SEABED_BASE_Y = -5.6;`,
`const SEABED_RELIEF = 3.0;`,
`const SURFACE_Y     = 5.0;`,
``,
`// Returns terrain height h in [-1, +1] given normalised coordinates (tx,tz) in [0,1]`,
`function bathymetry(tx, tz) {`,
`  let h = 0;`,
`  // Large basin swells`,
`  h += 0.50 * Math.sin(tx * 1.9 + 0.31) * Math.cos(tz * 1.5 + 0.64);`,
`  h += 0.36 * Math.cos(tx * 1.4 + 1.08) * Math.sin(tz * 1.8 + 0.90);`,
`  // Mid-ocean ridge (narrow elevated linear high)`,
`  const rx = tx - 0.52;`,
`  h += 0.28 * Math.exp(-rx * rx * 24) * Math.cos(tz * 2.4 + 0.45);`,
`  // Deep trench (narrow linear depression)`,
`  const tz2 = tz - 0.70;`,
`  h -= 0.24 * Math.exp(-tz2 * tz2 * 28) * Math.max(0, Math.cos(tx * 2.2 - 0.3));`,
`  // Continental-slope thickening toward X edges`,
`  const ex = Math.max(0, Math.abs(tx - 0.5) - 0.32) * 3.2;`,
`  h += 0.38 * ex * ex;`,
`  // Gentle abyssal undulations`,
`  h += 0.09 * Math.sin(tx * 4.2 + 0.78) * Math.cos(tz * 3.6 + 1.22);`,
`  h += 0.055 * Math.cos(tx * 6.4 - 0.51) * Math.sin(tz * 5.3 + 0.94);`,
`  return Math.max(-1, Math.min(1, h));`,
`}`,
``,
`// Seabed depth-colour palette (deep trench → ridge crest)`,
`const SB_PAL = ['#060e1c','#0a1830','#0d2244','#12305a','#1a3e72'];`,
``,
`function buildSeabedMesh(bounds, mW, mD) {`,
`  // seed shifts terrain deterministically per ocean region`,
`  const seed = (Number(bounds?.west ?? 70) * 7.3 + Number(bounds?.south ?? 8) * 13.1) % (2 * Math.PI);`,
`  const NW = 80, NH = 60;`,
`  const vc = (NW + 1) * (NH + 1);`,
`  const pos = new Float32Array(vc * 3);`,
`  const col = new Float32Array(vc * 3);`,
`  for (let j = 0; j <= NH; j++) {`,
`    for (let i = 0; i <= NW; i++) {`,
`      const tx = i / NW, tz = j / NH;`,
`      const h = bathymetry(tx + seed * 0.08, tz + seed * 0.05);`,
`      const x = (tx - 0.5) * mW;`,
`      const y = SEABED_BASE_Y + h * SEABED_RELIEF;`,
`      const z = (tz - 0.5) * mD;`,
`      const vi = j * (NW + 1) + i;`,
`      pos[vi*3]=x; pos[vi*3+1]=y; pos[vi*3+2]=z;`,
`      // depth-based colour`,
`      const norm = (h + 1) * 0.5;`,
`      const sn = Math.min(Math.floor(norm * (SB_PAL.length - 1)), SB_PAL.length - 2);`,
`      const st = (norm - sn / (SB_PAL.length - 1)) * (SB_PAL.length - 1);`,
`      const c = new THREE.Color(SB_PAL[sn]).lerp(new THREE.Color(SB_PAL[sn + 1]), st);`,
`      col[vi*3]=c.r; col[vi*3+1]=c.g; col[vi*3+2]=c.b;`,
`    }`,
`  }`,
`  const idx = [];`,
`  for (let j = 0; j < NH; j++) for (let i = 0; i < NW; i++) {`,
`    const a=j*(NW+1)+i, b=a+1, c=a+(NW+1), d=c+1;`,
`    idx.push(a,c,b, b,c,d);`,
`  }`,
`  const geo = new THREE.BufferGeometry();`,
`  geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));`,
`  geo.setAttribute('color',    new THREE.BufferAttribute(col, 3));`,
`  geo.setIndex(idx);`,
`  geo.computeVertexNormals();`,
`  return geo;`,
`}`,
``,
`// ═══════════════════════════════════════════════════════════════════════════`,
`// DATA LAYER — one horizontal mesh per depth slice (real scientific data).`,
`// Quad skipped if any corner missing → natural irregular boundary.`,
`// ═══════════════════════════════════════════════════════════════════════════`,
`function buildDataLayer(slice, bounds, mW, mD, variable, minV, maxV, anomMode, anomThr, thresh) {`,
`  const pts = slice?.points || [];`,
`  if (pts.length < 4) return null;`,
`  const west  = Number(bounds?.west  ?? bounds?.lon_min ?? 70);`,
`  const east  = Number(bounds?.east  ?? bounds?.lon_max ?? 85);`,
`  const south = Number(bounds?.south ?? bounds?.lat_min ?? 8);`,
`  const north = Number(bounds?.north ?? bounds?.lat_max ?? 22);`,
`  const lS = Math.max(east - west, 1e-4);`,
`  const laS = Math.max(north - south, 1e-4);`,
`  const latSet = new Set(), lonSet = new Set();`,
`  pts.forEach((p) => {`,
`    latSet.add(Math.round(Number(p.lat) * 50) / 50);`,
`    lonSet.add(Math.round(Number(p.lon) * 50) / 50);`,
`  });`,
`  const latArr = [...latSet].sort((a,b)=>a-b);`,
`  const lonArr = [...lonSet].sort((a,b)=>a-b);`,
`  if (latArr.length < 2 || lonArr.length < 2) return null;`,
`  const step = Math.max(1, Math.ceil(Math.max(latArr.length, lonArr.length) / 36));`,
`  const sLat = latArr.filter((_,i) => i%step===0);`,
`  const sLon = lonArr.filter((_,i) => i%step===0);`,
`  if (sLat.length < 2 || sLon.length < 2) return null;`,
`  const nL = sLat.length, nO = sLon.length;`,
`  const depth_m = Number(slice.depth_m ?? 0);`,
`  const layerY  = depthToY(depth_m);`,
`  const dm = new Map();`,
`  pts.forEach((p) => {`,
`    const la = Math.round(Number(p.lat)*50)/50;`,
`    const lo = Math.round(Number(p.lon)*50)/50;`,
`    const v = valueFor(p, variable);`,
`    if (Number.isFinite(v)) dm.set(la+'_'+lo, { v, ac: p.anomaly_c ?? null });`,
`  });`,
`  const vc = nL * nO;`,
`  const pos = new Float32Array(vc * 3);`,
`  const col = new Float32Array(vc * 3);`,
`  const vld = new Uint8Array(vc);`,
`  for (let j = 0; j < nL; j++) {`,
`    for (let i = 0; i < nO; i++) {`,
`      const la = sLat[j], lo = sLon[i];`,
`      const vi = j * nO + i;`,
`      pos[vi*3]   = ((lo-west)/lS-0.5)*mW;`,
`      pos[vi*3+1] = layerY;`,
`      pos[vi*3+2] = ((la-south)/laS-0.5)*mD;`,
`      const e = dm.get(la+'_'+lo);`,
`      if (e) {`,
`        let c;`,
`        if (anomMode) { c = anomalyColor(e.ac ?? (e.v-(minV+maxV)/2), anomThr); }`,
`        else { c = colorFor(e.v, minV, maxV, variable); }`,
`        if (thresh?.enabled &&`,
`          ((thresh.operator==='>' && e.v>thresh.value) ||`,
`           (thresh.operator==='<' && e.v<thresh.value) ||`,
`           Math.abs(e.v-thresh.value)<=thresh.tolerance)) c.set('#ffeb3b');`,
`        col[vi*3]=c.r; col[vi*3+1]=c.g; col[vi*3+2]=c.b;`,
`        vld[vi]=1;`,
`      }`,
`    }`,
`  }`,
`  const idx=[];`,
`  for (let j=0;j<nL-1;j++) for (let i=0;i<nO-1;i++) {`,
`    const a=j*nO+i,b=a+1,c=a+nO,d=c+1;`,
`    if (vld[a]&&vld[b]&&vld[c]&&vld[d]) { idx.push(a,c,b, b,c,d, b,c,a, d,c,b); }`,
`  }`,
`  if (!idx.length) return null;`,
`  const geo = new THREE.BufferGeometry();`,
`  geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));`,
`  geo.setAttribute('color',    new THREE.BufferAttribute(col, 3));`,
`  geo.setIndex(idx);`,
`  geo.computeVertexNormals();`,
`  return { geo, depth_m, layerY, sLat, sLon, west, lS, south, laS, mW, mD };`,
`}`,
``,
`// ═══════════════════════════════════════════════════════════════════════════`,
`// OceanSlab — main component`,
`// ═══════════════════════════════════════════════════════════════════════════`,
`export default function OceanSlab({`,
`  depthSlices=[],volumeData=null,grid=[],floats=[],variable='temperature',`,
`  depth=0,dataDepth=depth,bounds,opacity=0.95,verticalExaggeration=35,threshold,`,
`  source,dataSource,backupDate,regionName='Indian Ocean',`,
`  anomalyMode=false,anomalyThreshold=2.0,loading=false,onSelectMarker,`,
`}) {`,
`  const mountRef=useRef(null), sceneRef=useRef(null);`,
`  const hudRef=useRef(null), tooltipRef=useRef(null);`,
`  const dataRef=useRef({ depthSlices,volumeData,grid,floats,variable,depth,dataDepth,bounds,opacity,verticalExaggeration,threshold,source,dataSource,backupDate,regionName,anomalyMode,anomalyThreshold,loading });`,
`  useEffect(()=>{`,
`    dataRef.current={ depthSlices,volumeData,grid,floats,variable,depth,dataDepth,bounds,opacity,verticalExaggeration,threshold,source,dataSource,backupDate,regionName,anomalyMode,anomalyThreshold,loading };`,
`  },[depthSlices,volumeData,grid,floats,variable,depth,dataDepth,bounds,opacity,verticalExaggeration,threshold,source,dataSource,backupDate,regionName,anomalyMode,anomalyThreshold,loading]);`,
``,
`  useEffect(()=>{`,
`    const mount=mountRef.current; if(!mount) return undefined;`,
``,
`    // Renderer`,
`    const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});`,
`    renderer.setClearColor('#04080f',1);`,
`    renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));`,
`    mount.appendChild(renderer.domElement);`,
``,
`    // Scene`,
`    const scene=new THREE.Scene();`,
`    scene.background=new THREE.Color('#04080f');`,
`    scene.fog=new THREE.FogExp2('#04080f',0.015);`,
``,
`    // Camera — angled to show terrain + water layers together`,
`    const camera=new THREE.PerspectiveCamera(38,1,0.1,800);`,
`    camera.position.set(14,11,22);`,
`    camera.lookAt(0,-2,0);`,
``,
`    // Orbit`,
`    const controls=new OrbitControls(camera,renderer.domElement);`,
`    controls.enableDamping=true; controls.dampingFactor=0.055;`,
`    controls.target.set(0,-2,0);`,
`    controls.minDistance=8; controls.maxDistance=80;`,
`    controls.update();`,
``,
`    // Lighting — cool ocean palette`,
`    scene.add(new THREE.AmbientLight('#1a2f5a',3.6));`,
`    const sun=new THREE.DirectionalLight('#cce8ff',3.0); sun.position.set(12,28,18); scene.add(sun);`,
`    const fill=new THREE.DirectionalLight('#00c8aa',1.4); fill.position.set(-14,-10,-12); scene.add(fill);`,
`    const back=new THREE.DirectionalLight('#003366',1.6); back.position.set(-8,15,-20); scene.add(back);`,
``,
`    const mW=18, mD=14;`,
``,
`    // HUD`,
`    const hud=document.createElement('div');`,
`    hud.style.cssText='position:absolute;top:12px;left:14px;pointer-events:none;font-family:ui-sans-serif,system-ui,sans-serif;color:#e2e8f0;background:rgba(4,12,28,0.88);backdrop-filter:blur(8px);padding:8px 13px;border-radius:9px;border:1px solid rgba(0,200,170,0.25);font-size:12px;z-index:10;display:flex;flex-direction:column;gap:4px;box-shadow:0 4px 20px rgba(0,0,0,0.5)';`,
`    mount.appendChild(hud); hudRef.current=hud;`,
``,
`    const infoBadge=document.createElement('div');`,
`    infoBadge.style.cssText='position:absolute;bottom:52px;left:14px;pointer-events:none;font-family:ui-monospace,monospace;color:#4a7a9b;font-size:10px;z-index:10';`,
`    mount.appendChild(infoBadge);`,
``,
`    // Loading overlay`,
`    const loadOv=document.createElement('div');`,
`    loadOv.style.cssText='position:absolute;inset:0;display:none;align-items:center;justify-content:center;flex-direction:column;gap:12px;background:rgba(4,8,15,0.82);z-index:30;backdrop-filter:blur(4px)';`,
`    loadOv.innerHTML='<div style="width:44px;height:44px;border:3px solid #0e2244;border-top-color:#00c8aa;border-radius:50%;animation:spin 0.9s linear infinite"></div>'`,
`      +'<div style="color:#00c8aa;font-size:13px;font-weight:600">Fetching ocean data\u2026</div>'`,
`      +'<div style="color:#4a7a9b;font-size:11px;max-width:240px;text-align:center">L1 \u2192 L2 \u2192 Backup \u2192 Copernicus</div>';`,
`    const css=document.createElement('style');`,
`    css.textContent='@keyframes spin{to{transform:rotate(360deg)}}';`,
`    document.head.appendChild(css);`,
`    mount.appendChild(loadOv);`,
``,
`    // Tooltip`,
`    const tip=document.createElement('div');`,
`    tip.style.cssText='position:absolute;pointer-events:none;background:rgba(4,10,24,0.95);border:1px solid #00c8aa;color:#e2e8f0;padding:9px 13px;border-radius:9px;font-size:11px;font-family:ui-monospace,monospace;z-index:20;display:none;transform:translate(-50%,-118%);box-shadow:0 4px 20px rgba(0,200,170,0.2);white-space:nowrap;line-height:1.65';`,
`    mount.appendChild(tip); tooltipRef.current=tip;`,
``,
`    // Depth ruler`,
`    const rulerMat=new THREE.LineBasicMaterial({color:'#1e4a80',transparent:true,opacity:0.45});`,
`    [0,50,100,200,500,1000].forEach((d)=>{`,
`      const y=depthToY(d);`,
`      const rg=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(mW/2+0.15,y,0),new THREE.Vector3(mW/2+0.75,y,0)]);`,
`      scene.add(new THREE.Line(rg,rulerMat));`,
`    });`,
``,
`    // Ocean surface plane (very transparent — represents air/water boundary)`,
`    const surfGeo=new THREE.PlaneGeometry(mW+2,mD+2,1,1);`,
`    surfGeo.rotateX(-Math.PI/2); surfGeo.translate(0,SURFACE_Y,0);`,
`    const surfMat=new THREE.MeshStandardMaterial({color:'#003a6e',transparent:true,opacity:0.15,roughness:0.1,metalness:0.3,side:THREE.DoubleSide});`,
`    scene.add(new THREE.Mesh(surfGeo,surfMat));`,
``,
`    // Active depth selector plane`,
`    const selGeo=new THREE.PlaneGeometry(mW,mD); selGeo.rotateX(Math.PI/2);`,
`    const selMat=new THREE.MeshBasicMaterial({color:'#00c8aa',transparent:true,opacity:0.08,side:THREE.DoubleSide});`,
`    const selPlane=new THREE.Mesh(selGeo,selMat); scene.add(selPlane);`,
``,
`    // Argo floats`,
`    const fGeo=new THREE.SphereGeometry(0.32,12,12);`,
`    const fMat=new THREE.MeshStandardMaterial({color:'#00c8aa',emissive:'#009988',emissiveIntensity:1.0,roughness:0.12});`,
`    const markers=new THREE.InstancedMesh(fGeo,fMat,256); markers.count=0; scene.add(markers);`,
`    const tGeo=new THREE.BufferGeometry();`,
`    const tPos=new Float32Array(256*2*3);`,
`    tGeo.setAttribute('position',new THREE.BufferAttribute(tPos,3));`,
`    const tMat=new THREE.LineBasicMaterial({color:'#00c8aa',transparent:true,opacity:0.3});`,
`    scene.add(new THREE.LineSegments(tGeo,tMat));`,
``,
`    // Current arrows`,
`    const aGeo=new THREE.ConeGeometry(0.13,0.42,6); aGeo.rotateX(Math.PI/2);`,
`    const aMat=new THREE.MeshStandardMaterial({color:'#00c8aa',emissive:'#006699',emissiveIntensity:0.8});`,
`    const arrows=new THREE.InstancedMesh(aGeo,aMat,1200); arrows.count=0; arrows.visible=false; scene.add(arrows);`,
``,
`    // Dynamic objects`,
`    let seabedMesh=null, seabedWire=null;`,
`    let dataLayers=[], layerMeta=[];`,
`    const ray=new THREE.Raycaster(), ptr=new THREE.Vector2();`,
`    let hoveredFloat=null;`,
``,
`    // ── update ───────────────────────────────────────────────────────────`,
`    const update=()=>{`,
`      const cur=dataRef.current;`,
`      loadOv.style.display=cur.loading?'flex':'none';`,
``,
`      // Collect slices`,
`      const rawSlices=cur.depthSlices?.length?cur.depthSlices:cur.volumeData?.depth_slices||[];`,
`      let slices=[];`,
`      if (rawSlices.length>0) { slices=rawSlices; }`,
`      else if ((cur.grid||[]).length>0) {`,
`        [0,50,100,200,500,1000].forEach((dM)=>{`,
`          const decay=Math.exp(-dM/220);`,
`          slices.push({ depth_m:dM, points:(cur.grid||[]).map((p)=>({ ...p, depth_m:dM,`,
`            temperature_c:4+(Number(p.temperature_c??p.value??26)-4)*decay,`,
`            salinity_psu:34.7+(Number(p.salinity_psu??34.5)-34.7)*Math.exp(-dM/350),`,
`            current_u_ms:(p.current_u_ms??0)*decay, current_v_ms:(p.current_v_ms??0)*decay })) });`,
`        });`,
`      }`,
``,
`      // Remove old dynamic meshes`,
`      dataLayers.forEach(({mesh})=>{ scene.remove(mesh); mesh.geometry.dispose(); mesh.material.dispose(); });`,
`      dataLayers=[]; layerMeta=[];`,
`      if (seabedMesh) { scene.remove(seabedMesh); seabedMesh.geometry.dispose(); seabedMesh.material.dispose(); seabedMesh=null; }`,
`      if (seabedWire) { scene.remove(seabedWire); seabedWire.material.dispose(); seabedWire=null; }`,
``,
`      const lb=cur.bounds||{west:70,east:85,south:8,north:22};`,
``,
`      // Build seabed terrain`,
`      const sbGeo=buildSeabedMesh(lb,mW,mD);`,
`      seabedMesh=new THREE.Mesh(sbGeo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:0.75,metalness:0.04,side:THREE.DoubleSide}));`,
`      scene.add(seabedMesh);`,
`      seabedWire=new THREE.Mesh(sbGeo,new THREE.MeshBasicMaterial({color:'#003a55',wireframe:true,transparent:true,opacity:0.08}));`,
`      scene.add(seabedWire);`,
``,
`      if (!slices.length) {`,
`        hud.innerHTML='<div style="font-weight:700;color:#00c8aa">3D OCEAN SECTION \u00B7 '+(cur.regionName||'').toUpperCase()+'</div><div style="font-size:11px;color:#4a7a9b">No data \u2014 seabed is procedural fallback</div>';`,
`        return;`,
`      }`,
``,
`      const sorted=[...slices].sort((a,b)=>(a.depth_m??0)-(b.depth_m??0));`,
`      const allV=[];`,
`      sorted.forEach((s)=>(s.points||[]).forEach((p)=>{ const v=valueFor(p,cur.variable); if(Number.isFinite(v)) allV.push(v); }));`,
`      const minV=allV.length?Math.min(...allV):0, maxV=allV.length?Math.max(...allV):1;`,
``,
`      // Build data layers (one per depth slice)`,
`      sorted.forEach((slice,idx)=>{`,
`        const res=buildDataLayer(slice,lb,mW,mD,cur.variable,minV,maxV,cur.anomalyMode??false,cur.anomalyThreshold??2.0,cur.threshold);`,
`        if (!res) return;`,
`        const depFrac=idx/Math.max(sorted.length-1,1);`,
`        const op=Math.max(0.30,(cur.opacity??0.85)*(1.0-depFrac*0.50));`,
`        const mat=new THREE.MeshStandardMaterial({vertexColors:true,transparent:true,opacity:op,roughness:0.55,metalness:0.04,side:THREE.DoubleSide});`,
`        const mesh=new THREE.Mesh(res.geo,mat);`,
`        scene.add(mesh);`,
`        dataLayers.push({mesh});`,
`        layerMeta.push({...res,slice});`,
`      });`,
``,
`      selPlane.position.y=depthToY(Number(cur.depth||0));`,
``,
`      // Bounds helpers`,
`      const bW=Number(lb.west??70),bE=Number(lb.east??85),bS=Number(lb.south??8),bN=Number(lb.north??22);`,
`      const lSp=Math.max(bE-bW,1e-4), laSp=Math.max(bN-bS,1e-4);`,
``,
`      // Current arrows`,
`      if (cur.variable==='currents') {`,
`        arrows.visible=true; let ai=0;`,
`        const spts=sorted[0]?.points||[];`,
`        const step=Math.max(1,Math.floor(spts.length/1200));`,
`        const mtx=new THREE.Matrix4(),p=new THREE.Vector3(),r=new THREE.Euler(),q=new THREE.Quaternion(),sc=new THREE.Vector3();`,
`        for (let i=0;i<spts.length&&ai<1200;i+=step) {`,
`          const pt=spts[i], u=Number(pt.current_u_ms??0), v=Number(pt.current_v_ms??0), spd=Math.hypot(u,v);`,
`          if (spd<0.005) continue;`,
`          p.set(((Number(pt.lon)-bW)/lSp-0.5)*mW, depthToY(0)+0.6, ((Number(pt.lat)-bS)/laSp-0.5)*mD);`,
`          r.set(0,Math.atan2(u,v),0); q.setFromEuler(r); sc.set(1,1,Math.min(2.5,0.8+spd*4));`,
`          mtx.compose(p,q,sc); arrows.setMatrixAt(ai++,mtx);`,
`        }`,
`        arrows.count=ai; arrows.instanceMatrix.needsUpdate=true;`,
`      } else { arrows.visible=false; }`,
``,
`      // Argo markers`,
`      const fl=cur.floats||[], fc=Math.min(fl.length,256);`,
`      markers.count=fc;`,
`      const m2=new THREE.Matrix4(),p2=new THREE.Vector3(),q2=new THREE.Quaternion(),s2=new THREE.Vector3(1.1,1.1,1.1);`,
`      fl.slice(0,fc).forEach((f,i)=>{`,
`        const fx=((Number(f.lng??f.lon)-bW)/lSp-0.5)*mW;`,
`        const fz=((Number(f.lat)-bS)/laSp-0.5)*mD;`,
`        const fy=depthToY(Number(f.depth??f.data_depth??50));`,
`        p2.set(fx,fy,fz); m2.compose(p2,q2,s2); markers.setMatrixAt(i,m2);`,
`        const o=i*6;`,
`        tPos[o]=fx;tPos[o+1]=depthToY(0);tPos[o+2]=fz;`,
`        tPos[o+3]=fx;tPos[o+4]=fy;tPos[o+5]=fz;`,
`      });`,
`      markers.instanceMatrix.needsUpdate=true;`,
`      tGeo.attributes.position.needsUpdate=true;`,
``,
`      // HUD`,
`      const minD=sorted[0]?.depth_m??0, maxD=sorted[sorted.length-1]?.depth_m??1000;`,
`      const src=cur.dataSource==='copernicus_zarr'?'\uD83D\uDFE2 Copernicus L2':cur.dataSource==='backup_cache'?'\uD83D\uDCE6 Backup '+(cur.backupDate||''):cur.dataSource==='analytical_demo'?'\uD83C\uDF10 Analytical':'Cached';`,
`      const ab=cur.anomalyMode?'<span style="background:#c05000;color:#fff;padding:1px 6px;border-radius:4px;font-size:10px;margin-left:5px">ANOMALY</span>':'';`,
`      hud.innerHTML='<div style="font-weight:700;color:#00c8aa;letter-spacing:0.5px">3D OCEAN SECTION \u00B7 '+(cur.regionName||'').toUpperCase()+ab+'</div>'`,
`        +'<div style="display:flex;gap:10px;font-size:11px;color:#6a96ba">'`,
`        +'<span>Depth: <strong style="color:#00c8aa">'+(cur.depth??0)+'m</strong></span>'`,
`        +'<span>Layers: <strong style="color:#e2e8f0">'+sorted.length+' ('+minD+'\u2013'+maxD+'m)</strong></span>'`,
`        +'<span style="text-transform:capitalize">'+cur.variable+'</span>'`,
`        +'</div>'`,
`        +'<div style="font-size:10.5px;color:#4a7a9b;margin-top:1px">'+src+'</div>';`,
`      infoBadge.textContent='Seabed: procedural bathymetry | Layers: '+sorted.length+' | Exag: '+(cur.verticalExaggeration??35)+'\u00D7';`,
`    };`,
``,
`    update(); sceneRef.current={update};`,
``,
`    const resize=()=>{ const w=mount.clientWidth||1,h=mount.clientHeight||1; camera.aspect=w/h; camera.updateProjectionMatrix(); renderer.setSize(w,h,false); };`,
`    resize();`,
`    const obs=new ResizeObserver(resize); obs.observe(mount);`,
``,
`    // Pointer`,
`    const onMove=(e)=>{`,
`      const rect=renderer.domElement.getBoundingClientRect();`,
`      ptr.x=((e.clientX-rect.left)/rect.width)*2-1;`,
`      ptr.y=-((e.clientY-rect.top)/rect.height)*2+1;`,
`      ray.setFromCamera(ptr,camera);`,
`      // Float hit`,
`      const fh=ray.intersectObject(markers)[0];`,
`      if (fh&&dataRef.current.floats[fh.instanceId]) {`,
`        const f=dataRef.current.floats[fh.instanceId]; hoveredFloat=f;`,
`        renderer.domElement.style.cursor='pointer';`,
`        if (tip) {`,
`          tip.style.display='block';`,
`          tip.style.left=(e.clientX-rect.left)+'px';`,
`          tip.style.top=(e.clientY-rect.top)+'px';`,
`          const t=f.temperature!=null?Number(f.temperature).toFixed(2)+' \u00B0C':'\u2014';`,
`          const s=f.salinity!=null?Number(f.salinity).toFixed(2)+' PSU':'\u2014';`,
`          tip.innerHTML='<div style="color:#00c8aa;font-weight:700;margin-bottom:3px">Argo Float #'+(f.platform_number||f.id||'?')+'</div>'`,
`            +'<div>Depth: '+Math.round(f.depth??0)+' m</div>'`,
`            +'<div>Temp: '+t+'  Sal: '+s+'</div>'`,
`            +'<div style="color:#38bdf8;font-size:10px;margin-top:3px">Click for profile</div>';`,
`        }`,
`        return;`,
`      }`,
`      hoveredFloat=null;`,
`      // Data layer hit`,
`      const lms=dataLayers.map((dl)=>dl.mesh);`,
`      const hits=ray.intersectObjects(lms);`,
`      if (hits.length>0) {`,
`        renderer.domElement.style.cursor='crosshair';`,
`        const hit=hits[0], li=lms.indexOf(hit.object);`,
`        if (li>=0&&layerMeta[li]) {`,
`          const meta=layerMeta[li];`,
`          const lb2=dataRef.current.bounds||{west:70,east:85,south:8,north:22};`,
`          const hitLon=(hit.point.x/meta.mW+0.5)*meta.lS+meta.west;`,
`          const hitLat=(hit.point.z/meta.mD+0.5)*meta.laS+meta.south;`,
`          let bv=null, bd=Infinity;`,
`          (meta.slice?.points||[]).forEach((pt)=>{ const dl=(Number(pt.lat)-hitLat)**2+(Number(pt.lon)-hitLon)**2; if(dl<bd){bd=dl;bv=valueFor(pt,dataRef.current.variable);} });`,
`          if (tip) {`,
`            tip.style.display='block';`,
`            tip.style.left=(e.clientX-rect.left)+'px';`,
`            tip.style.top=(e.clientY-rect.top)+'px';`,
`            const latS=hitLat>=0?hitLat.toFixed(2)+'\u00B0 N':(-hitLat).toFixed(2)+'\u00B0 S';`,
`            const lonS=hitLon>=0?hitLon.toFixed(2)+'\u00B0 E':(-hitLon).toFixed(2)+'\u00B0 W';`,
`            const u={temperature:'\u00B0C',salinity:'PSU',currents:'m/s',chlorophyll:'mg/m\u00B3',oxygen:'mmol/m\u00B3',ph:'pH',nitrate:'mmol/m\u00B3',pco2:'\u03BCatm'};`,
`            const vs=Number.isFinite(bv)?bv.toFixed(3)+' '+(u[dataRef.current.variable]||''):'\u2014';`,
`            tip.innerHTML='<div style="color:#38bdf8;font-weight:700;margin-bottom:4px">Scientific Inspector</div>'`,
`              +'<div style="color:#6a96ba;font-size:10px">Location</div>'`,
`              +'<div>'+latS+' | '+lonS+'</div>'`,
`              +'<div>Depth: <strong style="color:#00c8aa">'+meta.depth_m.toFixed(1)+' m</strong></div>'`,
`              +'<div style="color:#6a96ba;font-size:10px;margin-top:3px">Measurement</div>'`,
`              +'<div style="text-transform:capitalize">'+dataRef.current.variable+': <strong style="color:#ffd166">'+vs+'</strong></div>';`,
`          }`,
`        }`,
`        return;`,
`      }`,
`      renderer.domElement.style.cursor='default';`,
`      if (tip) tip.style.display='none';`,
`    };`,
`    const onClick=()=>{ if(hoveredFloat) onSelectMarker?.(hoveredFloat); };`,
`    renderer.domElement.addEventListener('pointermove',onMove);`,
`    renderer.domElement.addEventListener('click',onClick);`,
``,
`    let frame;`,
`    const animate=()=>{ controls.update(); renderer.render(scene,camera); frame=requestAnimationFrame(animate); };`,
`    animate();`,
``,
`    return ()=>{`,
`      cancelAnimationFrame(frame); obs.disconnect();`,
`      renderer.domElement.removeEventListener('pointermove',onMove);`,
`      renderer.domElement.removeEventListener('click',onClick);`,
`      controls.dispose();`,
`      dataLayers.forEach(({mesh})=>{ mesh.geometry.dispose(); mesh.material.dispose(); });`,
`      if(seabedMesh){seabedMesh.geometry.dispose();seabedMesh.material.dispose();}`,
`      if(seabedWire){seabedWire.material.dispose();}`,
`      fGeo.dispose();fMat.dispose();aGeo.dispose();aMat.dispose();`,
`      tGeo.dispose();tMat.dispose();selGeo.dispose();selMat.dispose();`,
`      surfGeo.dispose();surfMat.dispose();rulerMat.dispose();`,
`      renderer.dispose(); css.remove();`,
`      [renderer.domElement,hud,infoBadge,tip,loadOv].forEach((el)=>{ if(mount.contains(el)) mount.removeChild(el); });`,
`      hudRef.current=null; tooltipRef.current=null;`,
`    };`,
`  },[onSelectMarker]); // eslint-disable-line react-hooks/exhaustive-deps`,
``,
`  useEffect(()=>{ sceneRef.current?.update(); },[depthSlices,volumeData,grid,floats,variable,depth,dataDepth,bounds,opacity,verticalExaggeration,threshold,source,dataSource,backupDate,regionName,anomalyMode,anomalyThreshold,loading]);`,
``,
`  return (`,
`    <div ref={mountRef} className="ocean-slab-canvas w-full h-full relative overflow-hidden"`,
`      aria-label="3D Ocean Section \u2014 seabed terrain with layered data volume" />`,
`  );`,
`}`,
].join('\n');

writeFileSync(
  'c:/ocean/oceanStream/frontend/src/components/ocean/OceanSlab.jsx',
  code,
  'utf8'
);

console.log('Written', code.split('\n').length, 'lines,', code.length, 'bytes');
